DECLARE
  V_PROC_EXISTS NUMBER := 0;  
BEGIN
  SELECT COUNT(*) 
  INTO V_PROC_EXISTS
  FROM ALL_SYNONYMS
  WHERE OWNER = 'PUBLIC'
  AND SYNONYM_NAME = 'SYNONYM_NAME';

  IF (V_PROC_EXISTS = 1) THEN
    EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYNONYM_NAME';
  END IF;
END;
/
