
DECLARE
  V_CONSTRAINT_EXISTS  NUMBER := 0;  
BEGIN
  SELECT COUNT(*)
  INTO V_CONSTRAINT_EXISTS 
  FROM ALL_CONSTRAINTS
  WHERE OWNER = 'OWNER'
  AND TABLE_NAME = 'TABLE_NAME' 
  AND CONSTRAINT_NAME = 'CONSTRAINT_NAME';

  IF (V_CONSTRAINT_EXISTS  = 1) THEN
    EXECUTE IMMEDIATE 'ALTER TABLE  OWNER.TABLE_NAME DROP CONSTRAINT CONSTRAINT_NAME';
  END IF;
END;
/
