
DECLARE
  V_TRIGGER_EXISTS  NUMBER := 0;  
BEGIN
  SELECT COUNT(*)
  INTO V_TRIGGER_EXISTS 
  FROM ALL_TRIGGERS
  WHERE OWNER = 'OWNER'
  AND TABLE_NAME = 'TABLE_NAME' 
  AND TRIGGER_NAME = 'TRIGGER_NAME';

  IF (V_TRIGGER_EXISTS  = 1) THEN
    EXECUTE IMMEDIATE 'DROP TRIGGER OWNER.TRIGGER_NAME';
  END IF;
END;
/

