DECLARE
  V_INDEX_EXISTS  NUMBER := 0;  
BEGIN
  SELECT COUNT(*)
  INTO V_INDEX_EXISTS 
  FROM ALL_INDEXES
  WHERE OWNER = 'OWNER'
  AND INDEX_NAME = 'INDEXNAME';

  IF (V_INDEX_EXISTS  = 0) THEN
    EXECUTE IMMEDIATE 'CREATE INDEX OWNER.INDEXNAME ON OWNER.TABLENAME(COLUM)';  
  END IF;    
END;
/
