
DECLARE
  V_PROC_EXISTS NUMBER := 0;  
BEGIN
  SELECT COUNT(*) 
  INTO V_PROC_EXISTS
  FROM ALL_PROCEDURES
  WHERE OWNER = 'OWNER'
  AND OBJECT_NAME = 'PROCEDURE_NAME';

  IF (V_PROC_EXISTS = 1) THEN
    EXECUTE IMMEDIATE 'DROP PROCEDURE OWNER.PROCEDURE_NAME';
  END IF;
END;
/
