DECLARE
  V_SEQUENCE_EXISTS  NUMBER := 0;  
BEGIN
  SELECT COUNT(*)
  INTO V_SEQUENCE_EXISTS 
  FROM ALL_SEQUENCES
  WHERE SEQUENCE_OWNER = 'OWNER'
  AND SEQUENCE_NAME = 'SEQUENCE_NAME';

  IF (V_SEQUENCE_EXISTS  = 0) THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE OWNER.SEQUENCE_NAME MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1 CACHE 20 ';  
  END IF;    
END;
/
