
SELECT 'DROP PUBLIC  SYNONYM ' || SYNONYM_NAME || ';' 
FROM ALL_SYNONYMS SYN
WHERE SYN.TABLE_OWNER = 'OWNER'
AND TABLE_NAME NOT IN (SELECT OBJECT_NAME FROM DBA_OBJECTS WHERE OWNER = SYN.TABLE_OWNER);

