SELECT TABLE_NAME
,      COLUMN_NAME
,      NUM_DISTINCT
,      SAMPLE_SIZE
,      TO_CHAR(LAST_ANALYZED, 'DD-MM-YY HH24:MI:SS') LAST_ANALYZED
,      NUM_BUCKETS
FROM   DBA_TAB_COLUMNS
WHERE  TABLE_NAME IN UPPER('TABLE_NAME')
ORDER BY LAST_ANALYZED DESC
;