
COLUMN  DEGREE FORMAT A2 HEADING "DEGREE";
SELECT INDEX_NAME
,      STATUS
,      NUM_ROWS
,      SAMPLE_SIZE
,      TO_CHAR(LAST_ANALYZED, 'DD-MM-YY HH24:MI:SS') LAST_ANALYZED
,      USER_STATS
,      DEGREE
FROM   DBA_INDEXES
WHERE  TABLE_NAME IN UPPER('TABLE_NAME')
ORDER BY LAST_ANALYZED DESC;