SELECT OPNAME
,      TARGET_DESC
,      SOFAR
,      TOTALWORK
,      UNITS
,      START_TIME
,      LAST_UPDATE_TIME
,      ELAPSED_SECONDS
,      MESSAGE
FROM   V$SESSION_LONGOPS
WHERE  START_TIME > TO_DATE('DDMMYYYYHH24MI','DDMMYYHH24MI') 
AND    SOFAR <> TOTALWORK
ORDER BY LAST_UPDATE_TIME DESC;



