SELECT TABLE_NAME
,      SAMPLE_SIZE
,      PCT_FREE
,      PCT_USED
,      NUM_ROWS
,      BLOCKS
,      AVG_ROW_LEN
,      TO_CHAR(LAST_ANALYZED, 'DD-MM-YY HH24:MI:SS') LAST_ANALYZED
FROM   DBA_TABLES
WHERE  TABLE_NAME IN UPPER('TABLE_NAME')
ORDER BY LAST_ANALYZED
;



