SELECT   TIMESTAMP, 
         LAG(TBL.WAARDE) OVER (ORDER BY TBL.TIMESTAMP) AS VALUE_BEFORE,
         LEAD(TBL.WAARDE) OVER (ORDER BY TBL.TIMESTAMP) AS VALUE_AFTER,
         TRUNC(TBL.WAARDE, 4) AS VALUE
FROM     MYTABLE TBL
GROUP BY TBL.TIMESTAMP
,        TBL.VALUE
;


