SELECT DISTINCT
  'CREATE USER '|| GRANTEE ||' IDENTIFIED EXTERNALLY DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT;'
FROM DBA_ROLE_PRIVS
;

SELECT
       'GRANT '|| GRANTED_ROLE || ' TO '|| GRANTEE ||';'
FROM DBA_ROLE_PRIVS
;

