SELECT
  ID,
  TIMESTAMP,
  SUM(DECODE(CODE, 'A', WAARDE, NULL)) A,
  SUM(DECODE(CODE, 'B', WAARDE, NULL)) B,
  SUM(DECODE(CODE, 'C', WAARDE, NULL)) C
FROM
  MYTABLE
WHERE CODE IN ('A', 'B', 'C')
GROUP BY TIMESTAMP, ID;


