DECLARE
  V_COLUMN_EXISTS NUMBER := 0;  
BEGIN
  SELECT COUNT(*) 
  INTO V_COLUMN_EXISTS
  FROM ALL_TAB_COLS
  WHERE OWNER = 'OWNER'
  AND TABLE_NAME = 'TABLE_NAME'
  AND COLUMN_NAME = 'COLUMN_NAME';

  IF (V_COLUMN_EXISTS = 1) THEN
    EXECUTE IMMEDIATE 'ALTER TABLE OWNER.TABLE_NAME RENAME COLUMN COLUMN_NAME TO COLUMN_NAME_OLD';   
  END IF;
END;
/
